apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-deployment
spec:
    replicas: 2
    selector:
       matchLabels:
          app: userapp
    template:
       metadata:
          labels:
             app: userapp
       spec:
          containers:
          - name: userapp
            image: idgroup/otus:userapp-1.0.1
            env:
              - name: DATASOURCE_URL
                valueFrom:
                  configMapKeyRef:
                    name: user-config
                    key: DATASOURCE_URL
              - name: DATASOURCE_USERNAME
                valueFrom:
                  configMapKeyRef:
                    name: user-config
                    key: DATASOURCE_USERNAME
              - name: DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: user-secret
                    key: DATASOURCE_PASSWORD
            ports:
              - name: web
                containerPort: 8080
