apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "hello-chart.fullname" . }}
              port:
                number: {{ .Values.service.port }}
        - path: /otusapp/idgroup(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "hello-chart.fullname" . }}
              port:
                number: {{ .Values.service.port }}
