apiVersion: v2
name: user-chart
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "userapp-1.0.1"

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database

